Controllers/AboutUsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Razor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class AboutUsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CoffeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CoffeeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoffeeController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
        public IActionResult Index()
        {
            return View(_context.Coffees.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            return View();
        }
        
        // post request to push new coffee to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCoffeeForm(Coffee coffee)
        {

            if (ModelState.IsValid)
            {
                _context.Coffees.Add(coffee);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Coffee created successfully";

                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Coffee was not created successfully";
            return View("Create", coffee);
        }
        
        // get request to get coffee detail
        public async Task<ActionResult> Detail(int? id)
        {
            var coffee = await _context.Coffees.FindAsync(id);

            if (coffee == null)
            {
                return NotFound();
            }
            
            return View(coffee);
        }
        
        // get request to retrieve data to edit page
        public async Task<ActionResult> Edit(int? id)
        {
            var coffee = await _context.Coffees.FindAsync(id);

            if (coffee == null)
            {
                return NotFound();
            }
            
            return View(coffee);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditCoffee(Coffee coffee)
        {
            _context.Coffees.Update(coffee);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to populate delete page
        public async Task<ActionResult> Delete(int? id)
        {
            var coffee = await _context.Coffees.FindAsync(id);
            
            if (coffee == null)
            {
                return NotFound();
            }
            
            return View(coffee);
        }
        
        // post request to edit db to remove coffee
        [HttpPost, ActionName("DeleteConfirm")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var coffee =  await _context.Coffees.FindAsync(id);
            
            if (coffee == null)
            {
                return NotFound();
            }
            
            _context.Coffees.Remove(coffee);
            await _context.SaveChangesAsync();
            TempData["Message"] = "Coffee deleted successfully";

            return RedirectToAction("Index");
        }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomerController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
        public IActionResult Index()
        {
            return View(_context.Customers.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            return View();
        }
        
        // post request to edit data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCustomerForm(Customer model)
        {

            if (ModelState.IsValid)
            {
                model.JoinDate = model.JoinDate.ToUniversalTime();
                
                _context.Customers.Add(model);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Customer created successfully";

                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Customer was not created successfully";
            return View("Create", model);
        }

        // get request to showcase customer specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var customer = await _context.Customers.FindAsync(id);

            if (customer == null)
            {
                return NotFound();
            }
            
            return View(customer);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            
            if (customer == null)
            {
                return NotFound();
            }
            
            return View(customer);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCustomer(Customer model)
        {
            _context.Customers.Update(model);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var customer = await _context.Customers.FindAsync(id);

            if (customer == null)
            {
                return NotFound();
            }
            
            return View(customer);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var customer =  await _context.Customers.FindAsync(id);
            
            if (customer == null)
            {
                return NotFound();
            }
            
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            TempData["Message"] = "Customer deleted successfully";
            
            return RedirectToAction("Index");
        }
    }
}

Controllers/MenuItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Razor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class MenuItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenuItemController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
           public IActionResult Index()
        {
            return View(_context.MenuItems.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            var roastAvailability = _context.Coffees
                .Select(c => new { Id = c.CoffeeId, Name = c.Name })
                .ToList();

            ViewBag.RoastOptions = new SelectList(roastAvailability, "Id", "Name"); 
            
            return View();
        }
        
        // post request to edit data
        public async Task<IActionResult> CreateMenuItemForm(MenuItem model)
        {
            _context.MenuItems.Add(model);
            await _context.SaveChangesAsync();
            
            ViewBag.Message = "menuItem created successfully";
            
            return RedirectToAction("Index");
        }

        // get request to showcase menuItem specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var menuItem = await _context.MenuItems.FindAsync(id);

            if (menuItem == null)
            {
                return NotFound();
            }
            
            return View(menuItem);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var menuItem = await _context.MenuItems.FindAsync(id);
            
            if (menuItem == null)
            {
                return NotFound();
            }
            
            return View(menuItem);
        }
        
        // post request to push changes to db
        public async Task<IActionResult> EditMenuItem(MenuItem model)
        {
            _context.MenuItems.Update(model);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var menuItem = await _context.MenuItems.FindAsync(id);

            if (menuItem == null)
            {
                return NotFound();
            }
            
            return View(menuItem);
        }
        
        // post request to push changes to db
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var menuItem =  await _context.MenuItems.FindAsync(id);
            
            if (menuItem == null)
            {
                return NotFound();
            }
            
            _context.MenuItems.Remove(menuItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_BlankLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Coffee Title _Layout </title>
    
    <script type="importmap"></script>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Cofe </a>
            <a class="navbar-brand" asp-area="" asp-controller="MenuItem" asp-action="Index">Café Menu</a>
            <a class="navbar-brand" asp-area="" asp-controller="AboutUs" asp-action="Index">About Us</a>
            <a class="navbar-brand" asp-area="" asp-controller="ManagerBackend" asp-action="Index">Backend Analytics</a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
          
            
        </div>
    </nav>
</header>

<div style="background-color: #f0ffff"; class="container">
    <main role="main" class="pb-3">
        
        @RenderBody()
        
    </main>
</div>

<footer class="border-top footer text-muted">
    
    <div class="container">
        &copy; 2025 - Cofe
    </div>
</footer>
         

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<!-- Optional: Add Bootstrap JS and dependencies (jQuery and Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_CoffeeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Coffee Title _Layout </title>
    
    <script type="importmap"></script>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Cofe </a>
            <a class="navbar-brand" asp-area="" asp-controller="MenuItem" asp-action="Index">Café Menu</a>
            <a class="navbar-brand" asp-area="" asp-controller="AboutUs" asp-action="Index">About Us</a>
            <a class="navbar-brand" asp-area="" asp-controller="ManagerBackend" asp-action="Index">Backend Analytics</a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
          
            
        </div>
    </nav>
</header>

<div style="background-color: #f0ffff"; class="container">
    <main role="main" class="pb-3">
        
        @RenderBody()
        
    </main>
</div>

<footer class="border-top footer text-muted">
    
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                &copy; 2025 - Cofe
                <br>
                Cofe Stack
                <ul>
                    <li>HTML, CSS, .NET Core</li>
                    <li>Bootstrap</li>
                    <li>AWS</li>
                </ul>
            </div>
            <div class="col">
                Darren Fisher
                <br>
                Full Stack Engineer
                <br>
                My Stack:
                <ul>
                    <li>SQL, Python, C#, TS</li>
                    <li>React, .Net, Node</li>
                    <li>AWS, GCP, Azure</li>
                </ul>
            </div>
            <div class="col">
                Linkedin
                <br>
                Github
            </div>
        </div>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<!-- Optional: Add Bootstrap JS and dependencies (jQuery and Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Coffee Title _Layout </title>

    <script type="importmap"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>

</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">

            <a class="navbar-brand" asp-area="" asp-controller="Coffee" asp-action="Index"> Cofe </a>
            <a class="navbar-brand" asp-area="" asp-controller="MenuItem" asp-action="Index">Café Menu</a>
            <a class="navbar-brand" asp-area="" asp-controller="AboutUs" asp-action="Index">About Us</a>
            <a class="navbar-brand" asp-area="" asp-controller="ManagerBackend" asp-action="Index">Backend Analytics</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>


        </div>
    </nav>
</header>

<div style="background-color: #f0ffff"; class="container">
    <main role="main" class="pb-3">

        @RenderBody()

    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Cofe - .Net app
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<!-- Optional: Add Bootstrap JS and dependencies (jQuery and Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Coffee Title _Layout </title>
    
    <script type="importmap"></script>
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            
            <a class="navbar-brand" asp-area="" asp-controller="Coffee" asp-action="Index"> CLassNav Top Bar </a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                
                <ul class="navbar-nav flex-grow-1">

                    <li class="nav-item">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Coffee
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Coffee" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Coffee" asp-action="Details">Details</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Coffee" asp-action="Create">Create</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Coffee" asp-action="Edit">Edit</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Coffee" asp-action="Delete">Delete</a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    <li class="nav-item">

                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                User
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Index">Home</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Details">Details</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Create">Create</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Edit">Edit</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Delete">Delete</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    
                </ul>
                
            </div>
            
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown button
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Index">User Home</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Details">Details</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Create">Create</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Edit">Edit</a>
                </li>
                <li>
                    <a class="dropdown-item" asp-area="" asp-controller="Customer" asp-action="Delete">Delete</a>
                </li>
            </ul>
        </div>
        
        <div>
            @RenderBody()
        </div>
        
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Coffee - WebApplication2 
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<!-- Optional: Add Bootstrap JS and dependencies (jQuery and Popper.js) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

@await RenderSectionAsync("Scripts", required: false)

</body>
</html>