Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
        public async Task<IActionResult> Index()
        {
            var orders = await _context.Orders.ToListAsync();
            return View(orders);
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            ViewBag.Customers = new SelectList(_context.Customers
                .OrderBy(x=> x.JoinDate)
                .Take(10)
                .Select(c => new 
            {
                c.CustomerId,
                FullName = c.FirstName + " " + c.LastName
            }), "CustomerId", "FullName");
            
            return View();
        }
        
        // post request to edit data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrderForm([Bind("CustomerId,OrderDate")] Order model)
        {
           
            if (ModelState.IsValid)
            {
                model.OrderDate = model.OrderDate.ToUniversalTime();
                
                _context.Orders.Add(model);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Order created successfully";
               
                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Order was not created successfully";
            return View("Create", model);
        }
        
        
        
        // -------------------
        
        // get request to showcase Order specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var order = await _context.Orders
                .Include(o => o.Customer)
                .FirstOrDefaultAsync(o => o.OrderId == id);

            if (order == null)
            {
                return NotFound();
            }
            
            return View(order);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            
            if (order == null)
            {
                return NotFound();
            }
            
            return View(order);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOrder(Order model)
        {
            if (ModelState.IsValid)
            {
                _context.Orders.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Error updating model";
            return RedirectToAction("Edit");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var order = await _context.Orders.FindAsync(id);

            if (order == null)
            {
                return NotFound();
            }
            
            return View(order);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var order =  await _context.Orders.FindAsync(id);
            
            if (order == null)
            {
                return NotFound();
            }
            
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            TempData["Message"] = "Order deleted successfully";
            
            return RedirectToAction("Index");
        }
    }
}

Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class OrderDetailController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderDetailController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.OrderDetails.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            ViewBag.Order = new SelectList(_context.Orders
                .OrderBy(x => x.OrderDate)
                .Take(10)
                .Select(x => new 
            {
                x.OrderId
            }), "OrderId", "OrderId");
            
            ViewBag.MenuItem = new SelectList(_context.MenuItems.Select(x => new 
            {
                x.MenuItemId,
                x.Name,
            }), "MenuItemId", "Name");
            
            return View();
        }
        
        // post request to edit data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrderDetailForm(OrderDetail model)
        {

            if (ModelState.IsValid)
            {
                
                _context.OrderDetails.Add(model);
                await _context.SaveChangesAsync();

                TempData["Message"] = "OrderDetail created successfully";

                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "OrderDetail was not created successfully";
            return View("Create", model);
        }

        // get request to showcase OrderDetail specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var orderDetail = await _context.OrderDetails.FindAsync(id);

            if (orderDetail == null)
            {
                return NotFound();
            }
            
            return View(orderDetail);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var orderDetail = await _context.OrderDetails.FindAsync(id);
            
            if (orderDetail == null)
            {
                return NotFound();
            }
            
            return View(orderDetail);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOrder(OrderDetail model)
        {
            _context.OrderDetails.Update(model);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var orderDetail = await _context.OrderDetails.FindAsync(id);

            if (orderDetail == null)
            {
                return NotFound();
            }
            
            return View(orderDetail);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var orderDetail =  await _context.OrderDetails.FindAsync(id);
            
            if (orderDetail == null)
            {
                return NotFound();
            }
            
            _context.OrderDetails.Remove(orderDetail);
            await _context.SaveChangesAsync();
            TempData["Message"] = "OrderDetail deleted successfully";

            return RedirectToAction("Index");
        }
    }
}

Views/OrderDetail/Create.cshtml
@model WebApplication2.Models.OrderDetail

@{
    ViewBag.Title = "Create Order Detail";
    Layout = "_CoffeeLayout";
}

<link href="~/css/OrderDetailStyle.css" rel="stylesheet" type="text/css" />


<h1 class="mb-4">Add a new OrderDetail</h1>

@using (Html.BeginForm("CreateOrderDetailForm", "OrderDetail", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="card p-4 shadow-sm">
        <h4 class="mb-3">Create OrderDetail</h4>

        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
        
        @* <div class="form-group mb-3"> *@
        @*     @Html.LabelFor(model => model.OrderId, new { @class = "form-label fw-bold" }) *@
        @*     @Html.TextBoxFor(model => model.OrderId, new { @class = "form-control", placeholder = "Enter the order id" }) *@
        @*     @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" }) *@
        @* </div> *@

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.OrderId, new { @class = "form-label fw-bold" })
            @Html.DropDownListFor(model => model.OrderId, (SelectList)ViewBag.Order, "What is your order?", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
        </div>
        
        <div class="form-group mb-3">
            @Html.LabelFor(model => model.MenuItemId, new { @class = "form-label fw-bold" })
            @Html.DropDownListFor(model => model.MenuItemId, (SelectList)ViewBag.MenuItem, "Select a menu item", new { @class = "form-select" })
            @Html.ValidationMessageFor(model => model.MenuItemId, "", new { @class = "text-danger" })
        </div>
        
        @* <div class="form-group mb-3"> *@
        @*     @Html.LabelFor(model => model.MenuItemId, new { @class = "form-label fw-bold" }) *@
        @*     @Html.TextAreaFor(model => model.MenuItemId, new { @class = "form-control", placeholder = "What did you order" }) *@
        @*     @Html.ValidationMessageFor(model => model.MenuItemId, "", new { @class = "text-danger" }) *@
        @* </div> *@

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.Quantity, new { @class = "form-label fw-bold" })
            @Html.TextAreaFor(model => model.Quantity, new { @class = "form-control", placeholder = "Enter Quantity in order", type = "number", min = "1", required = "required"})
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
        
        <div class="d-flex gap-2 mt-3">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="@Url.Action("Index", "OrderDetail")" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
}

<div>
    end
</div>

Views/OrderDetail/Delete.cshtml
@model WebApplication2.Models.OrderDetail

<link href="~/css/OrderDetailStyle.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Delete Order Detail";
    Layout = "_CoffeeLayout";
}

@using (Html.BeginForm("DeleteConfirm", "Order", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        <h3>Delete Order Detail</h3>

        <div>
            <p>@Model.OrderDetailId, </p>
            <div>
                <p>Customer: @Model.OrderId </p>
                <p>Date: @Model.MenuItemId </p>
            </div>
            
            @Html.HiddenFor(model => model.OrderId)
        </div>

        <div>
            <button type="submit" class="btn btn-danger">Yes</button>
            @Html.ActionLink("No", "Index", "OrderDetail",  new {@class="btn btn-secondary"})
        </div>
    </div>
}

Views/OrderDetail/Details.cshtml
@model WebApplication2.Models.OrderDetail


@{
    ViewBag.Title = "Order Details";
    Layout = "_CoffeeLayout";
}

<link href="~/css/OrderStyle.css" rel="stylesheet" type="text/css" />

<h1 style="margin-bottom: 20px">Order Details</h1>

<div class="order-details-container">
    <div class="order-image">
        <img src="~/images/order-image.jpg" alt="order Image" class="img-fluid" />
    </div>

    <div class="order-info">
        <h2>@Model.OrderDetailId</h2>
        <div class="order-meta">
            <span><strong>MenuItem:</strong> @Model.MenuItem</span>
            <span><strong>Quantity:</strong> @Model.Quantity</span>
            <span><strong>OrderId:</strong> @Model.OrderId</span>
        </div>
    </div>
</div>

<footer>
    footer content
</footer>

Views/OrderDetail/Edit.cshtml
@model WebApplication2.Models.OrderDetail

@{
    ViewBag.Title = "Order Detail Edit Page";
    Layout = "_CoffeeLayout";
}

<link href="~/css/OrderDetailStyle.css" rel="stylesheet" type="text/css" />

<h1 style="margin-bottom: 10px"> Edit Order Detail </h1>


<div>
    <form asp-action="Edit" method="post">
        <input type="hidden" asp-for="OrderDetailId"/>

        <div class="form-group">
            <label asp-for="OrderId"></label>
            <input asp-for="OrderId" class="form-control"/>
        </div>
        <div class="form-group">
            <label asp-for="MenuItemId"></label>
            <input asp-for="MenuItemId" class="form-control"/>
        </div>
        <div class="form-group">
            <label asp-for="Quantity"></label>
            <input asp-for="Quantity" class="form-control"/>
        </div>
        <button type="submit" class="btn btn-primary"> Save Changes </button>
        <a href="@Url.Action("Index", "OrderDetail")" class="btn btn-secondary">Cancel</a>

    </form>
</div>

<div>
    edit done
</div>

Views/OrderDetail/Index.cshtml
@model IEnumerable<WebApplication2.Models.OrderDetail>

<link href="~/css/OrderDetailStyle.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Order Detail";
    Layout = "_CoffeeLayout";
}


<h1 style="margin-bottom: 10px"> Order Detail Home </h1>

<div>
    <table class="table">
        <thead>
        <tr>
            <th>OrderDetailID</th>
            <th>OrderID</th>
            <th>MenuItemId</th>
            <th>Quantity</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @{
            foreach (var orderDetail in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(orderDetailList => orderDetail.OrderDetailId)
                    </td>
                    <td>
                        @Html.DisplayFor(orderDetailList => orderDetail.OrderId)
                    </td>
                    <td>
                        @Html.DisplayFor(orderDetailList => orderDetail.MenuItemId)
                    </td>
                    <td>
                        @Html.DisplayFor(orderDetailList => orderDetail.Quantity)
                    </td>
                    
                    <td>
                        <a asp-action="Edit" asp-route-id="@orderDetail.OrderId">Edit</a>
                        <a asp-action="Delete" asp-route-id="@orderDetail.OrderId">Delete</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>
</div>


<div>
    <a asp-controller="OrderDetail" asp-action="Create" class="fw-bold" style="padding: 5px"> Create </a>
    <a asp-controller="ManagerBackend" asp-action="Index" class="fw-bold" style="padding: 5px"> Backend Hub </a>
</div>