Controllers/CoffeeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CoffeeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoffeeController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
        public IActionResult Index()
        {
            return View(_context.Coffees.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            return View();
        }
        
        // post request to push new coffee to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCoffeeForm(Coffee coffee)
        {

            if (ModelState.IsValid)
            {
                _context.Coffees.Add(coffee);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Coffee created successfully";

                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Coffee was not created successfully";
            return View("Create", coffee);
        }
        
        // get request to get coffee detail
        public async Task<ActionResult> Detail(int? id)
        {
            var coffee = await _context.Coffees.FindAsync(id);

            if (coffee == null)
            {
                return NotFound();
            }
            
            return View(coffee);
        }
        
        // get request to retrieve data to edit page
        public async Task<ActionResult> Edit(int? id)
        {
            var coffee = await _context.Coffees.FindAsync(id);

            if (coffee == null)
            {
                return NotFound();
            }
            
            return View(coffee);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditCoffee(Coffee coffee)
        {
            _context.Coffees.Update(coffee);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to populate delete page
        public async Task<ActionResult> Delete(int? id)
        {
            var coffee = await _context.Coffees.FindAsync(id);
            
            if (coffee == null)
            {
                return NotFound();
            }
            
            return View(coffee);
        }
        
        // post request to edit db to remove coffee
        [HttpPost, ActionName("DeleteConfirm")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var coffee =  await _context.Coffees.FindAsync(id);
            
            if (coffee == null)
            {
                return NotFound();
            }
            
            _context.Coffees.Remove(coffee);
            await _context.SaveChangesAsync();
            TempData["Message"] = "Coffee deleted successfully";

            return RedirectToAction("Index");
        }
    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomerController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
        public IActionResult Index()
        {
            return View(_context.Customers.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            return View();
        }
        
        // post request to edit data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCustomerForm(Customer model)
        {

            if (ModelState.IsValid)
            {
                model.JoinDate = model.JoinDate.ToUniversalTime();
                
                _context.Customers.Add(model);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Customer created successfully";

                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Customer was not created successfully";
            return View("Create", model);
        }

        // get request to showcase customer specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var customer = await _context.Customers.FindAsync(id);

            if (customer == null)
            {
                return NotFound();
            }
            
            return View(customer);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            
            if (customer == null)
            {
                return NotFound();
            }
            
            return View(customer);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCustomer(Customer model)
        {
            _context.Customers.Update(model);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var customer = await _context.Customers.FindAsync(id);

            if (customer == null)
            {
                return NotFound();
            }
            
            return View(customer);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var customer =  await _context.Customers.FindAsync(id);
            
            if (customer == null)
            {
                return NotFound();
            }
            
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            TempData["Message"] = "Customer deleted successfully";
            
            return RedirectToAction("Index");
        }
    }
}

Controllers/MenuItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.Razor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class MenuItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenuItemController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
           public IActionResult Index()
        {
            return View(_context.MenuItems.ToList());
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            var roastAvailability = _context.Coffees
                .Select(c => new { Id = c.CoffeeId, Name = c.Name })
                .ToList();

            ViewBag.RoastOptions = new SelectList(roastAvailability, "Id", "Name"); 
            
            return View();
        }
        
        // post request to edit data
        public async Task<IActionResult> CreateMenuItemForm(MenuItem model)
        {
            _context.MenuItems.Add(model);
            await _context.SaveChangesAsync();
            
            ViewBag.Message = "menuItem created successfully";
            
            return RedirectToAction("Index");
        }

        // get request to showcase menuItem specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var menuItem = await _context.MenuItems.FindAsync(id);

            if (menuItem == null)
            {
                return NotFound();
            }
            
            return View(menuItem);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var menuItem = await _context.MenuItems.FindAsync(id);
            
            if (menuItem == null)
            {
                return NotFound();
            }
            
            return View(menuItem);
        }
        
        // post request to push changes to db
        public async Task<IActionResult> EditMenuItem(MenuItem model)
        {
            _context.MenuItems.Update(model);
            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var menuItem = await _context.MenuItems.FindAsync(id);

            if (menuItem == null)
            {
                return NotFound();
            }
            
            return View(menuItem);
        }
        
        // post request to push changes to db
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var menuItem =  await _context.MenuItems.FindAsync(id);
            
            if (menuItem == null)
            {
                return NotFound();
            }
            
            _context.MenuItems.Remove(menuItem);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }
        
        // get request to show index page
        public async Task<IActionResult> Index()
        {
            var orders = await _context.Orders.ToListAsync();
            return View(orders);
        }
        
        // get request to show create page
        public IActionResult Create()
        {
            ViewBag.Customers = new SelectList(_context.Customers
                .OrderBy(x=> x.JoinDate)
                .Take(10)
                .Select(c => new 
            {
                c.CustomerId,
                FullName = c.FirstName + " " + c.LastName
            }), "CustomerId", "FullName");
            
            return View();
        }
        
        // post request to edit data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrderForm([Bind("CustomerId,OrderDate")] Order model)
        {
           
            if (ModelState.IsValid)
            {
                model.OrderDate = model.OrderDate.ToUniversalTime();
                
                _context.Orders.Add(model);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Order created successfully";
               
                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Order was not created successfully";
            return View("Create", model);
        }
        
        
        
        // -------------------
        
        // get request to showcase Order specific data
        public async Task<IActionResult> Detail(int? id)
        {
            var order = await _context.Orders
                .Include(o => o.Customer)
                .FirstOrDefaultAsync(o => o.OrderId == id);

            if (order == null)
            {
                return NotFound();
            }
            
            return View(order);
        }
        
        // get request to showcasce model data
        public async Task<IActionResult> Edit(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            
            if (order == null)
            {
                return NotFound();
            }
            
            return View(order);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOrder(Order model)
        {
            if (ModelState.IsValid)
            {
                _context.Orders.Update(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            
            TempData["Message"] = "Error updating model";
            return RedirectToAction("Edit");
        }
        
        // get request to get to the delete page with model filled in
        public async Task<IActionResult> Delete(int id)
        {
            var order = await _context.Orders.FindAsync(id);

            if (order == null)
            {
                return NotFound();
            }
            
            return View(order);
        }
        
        // post request to push changes to db
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var order =  await _context.Orders.FindAsync(id);
            
            if (order == null)
            {
                return NotFound();
            }
            
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            TempData["Message"] = "Order deleted successfully";
            
            return RedirectToAction("Index");
        }
    }
}

Views/ManagerBackend/Index.cshtml
@model List<WebApplication2.Models.Coffee>

<link href="~/css/CoffeeStyle.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "title";
    Layout = "_CoffeeLayout";
}

<div>
    <h1>
        Analytics and Backend
    </h1>
    <p>
        What is this page?
    <ul>
        <li>
            Showcase some data analytics
        </li>
        <li>
            Showcase what is happening on the "backend" of this website as it navigates through the different model, views, & controllers
        </li>
        <li>
            Showcase code stack: .Net, Html, CSS, TS, postgres, docker, & git
        </li>
    </ul>

    </p>
    <p>
        Below we xyz...
    </p>

</div>

<div>
    <h4>Coffee Data: </h4>
    <div>
        <a asp-controller="Coffee" asp-action="Index"> Index </a>
        <a asp-controller="Coffee" asp-action="Create"> Create </a>
    </div>
</div>

<div>
    <h4>Menu Item Data: </h4>
    <div>
        <a asp-controller="MenuItem" asp-action="Index"> Index </a>
        <a asp-controller="MenuItem" asp-action="Create"> Create </a>
    </div>
</div>

<div>
    <h4>Customer Data: </h4>
    <div>
        <a asp-controller="Customer" asp-action="Index"> Index </a>
        <a asp-controller="Customer" asp-action="Create"> Create </a>
    </div>
</div>

<div>
    <h4>Order Data: </h4>
    <div>
        <a asp-controller="Order" asp-action="Index"> Index </a>
        <a asp-controller="Order" asp-action="Create"> Create </a>
    </div>
</div>

<div>
    <h4>Order Detail Data: </h4>
    <div>
        <a asp-controller="OrderDetail" asp-action="Index"> Index </a>
        <a asp-controller="OrderDetail" asp-action="Create"> Create </a>
    </div>
</div>

Views/ManagerBackend/ManagerBackendHub.cshtml
@model List<WebApplication2.Models.Coffee>

<link href="~/css/CoffeeStyle.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "title";
    Layout = "_CoffeeLayout";
}

<div>
    <h1>
        Analytics and Backend
    </h1>
    <p>
        What is this page? 
        <ul>
            <li>
                Showcase some data analytics
            </li>
            <li>
                 Showcase what is happening on the "backend" of this website as it navigates through the different model, views, & controllers
            </li>
            <li>
                 Showcase code stack: Html, CSS, .Net, postgres, docker, git,
            </li>
        </ul>

    </p>
    <p>
        Below we xyz...
    </p>
    
</div>

<div class="detailTable">
    <div class="container text-center" style="font-size: 25px; margin-top: 25px; margin-bottom: 25px">
        <div>
            <div class="row">
                <div class="col">
                    <a asp-area="" asp-controller="Coffee" asp-action="Index"> Coffee </a>
                </div>
                <div class="col">
                    <a asp-area="" asp-controller="Coffee" asp-action="Create"> Create </a>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <a asp-area="" asp-controller="Coffee" asp-action="Edit"> Edit </a>
                </div>
                <div class="col">
                    <a asp-area="" asp-controller="Coffee" asp-action="Delete"> Delete </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="detailTable">
    <div class="container text-center" style="font-size: 25px; margin-top: 25px; margin-bottom: 25px">
        <div>
            <div class="row">
                <div class="col">
                    <a asp-area="" asp-controller="Customer" asp-action="Index"> Customer </a>
                </div>
                <div class="col">
                    <a asp-area="" asp-controller="Customer" asp-action="Create"> Create </a>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <a asp-area="" asp-controller="Customer" asp-action="Edit"> Edit </a>
                </div>
                <div class="col">
                    <a asp-area="" asp-controller="Customer" asp-action="Delete"> Delete </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="detailTable">
    <div class="container text-center" style="font-size: 25px; margin-top: 25px; margin-bottom: 25px">
        <div>
            <div class="row">
                <div class="col">
                    <a asp-area="" asp-controller="Sale" asp-action="Index"> Sale </a>
                </div>
                <div class="col">
                    <a asp-area="" asp-controller="Sale" asp-action="Create"> Create </a>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <a asp-area="" asp-controller="Sale" asp-action="Edit"> Edit </a>
                </div>
                <div class="col">
                    <a asp-area="" asp-controller="Sale" asp-action="Delete"> Delete </a>
                </div>
            </div>
        </div>
    </div>
</div>